from collections.abc import Sequence
from typing import Protocol

from orchestrator.app.domain.entities import TrainingTask
from orchestrator.app.domain.enums import TrainingTaskStatus


class TrainingTaskRepository(Protocol):
    def get(self, task_id: str) -> TrainingTask | None: ...

    def list(self) -> Sequence[TrainingTask]: ...

    def list_by_job(self, job_id: int) -> Sequence[TrainingTask]: ...

    def list_by_status(self, status: TrainingTaskStatus) -> Sequence[TrainingTask]: ...

    def list_by_trainer(self, trainer_node_id: str) -> Sequence[TrainingTask]: ...

    def upsert(self, task: TrainingTask) -> TrainingTask: ...

    def claim_next_pending(self, trainer_node_id: str) -> TrainingTask | None: ...
